### ISSUE TITLE
1.16 Support

### ISSUE THREAD

**Issue by 132ikl** [Arnuh/ArmorEquipEvent#28]
In 1.16 Netheritie armor was added, and if the plugin uses a lower `api-version` than 1.16 for whatever reason the `Material` of Netherite armor appears as `AIR`. If you update the `api-version` to 1.16 this will likely break lower version compatibility, so I'm not sure how you want to handle this. Either way, a working 1.16 fork can be found at [132ikl/ArmorEquipEvent](https://github.com/132ikl/ArmorEquipEvent).

**Comment by Arnuh** [comment]
Well I forgot to specify this issue in the commit but https://github.com/Arnuh/ArmorEquipEvent/commit/2bad3f3f24106bc2596093d0e58aaea8e48b09c5 now specifies the api version of 1.14 which seems to solve the problem. No reason bumping the version higher since the plugin doesn't use anything in a higher api version.

**Comment by 132ikl** [comment]
Perfect. Could you also make a release? Thanks

**Comment by Arnuh** [comment]
https://jenkins.arnah.ca/view/Minecraft/job/ArmorEquipEvent/ will have latest builds. I'll do a proper release on Github/Spigot once I know nothing else is broken in 1.16
